#!/usr/bin/env python

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os

def main():
	try:
		home = os.environ["SICILIA"]
	except:
		home = ".."

#	sys.path.insert(0,home+"/lib/python/MrfTiming/")
#	sys.path.insert(0,home+"/app/cttihw")
#	sys.path.insert(0, '../../pyapi/')
	actual_dir=os.path.dirname(os.path.realpath(__file__))
	os.chdir(actual_dir)
	apipythonpath=os.path.normpath(os.getcwd()+os.sep+os.pardir)+"/pyapi/"
	sys.path.insert(1,apipythonpath)
#	sys.path.insert(0,os.getcwd())
	import eventreceiver
#	print sys.path
	eventreceiver.main()

if __name__ == "__main__":
	main()
